[workspace]
members = [
    "crates/rore-core",
    "crates/rore-macros",
    "crates/rore-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2025"
authors = ["Rore Team"]
license = "MIT or Apache-2.0"
repository = "https://github.com/davlatov-tech/Rore.git"
description = "The Post-Web Interface Engine. Native, Rust, WGPU."

[workspace.dependencies]
winit = "0.29"
wgpu = "0.19"
taffy = "0.3"
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
clap = { version = "4.4", features = ["derive"] }